### ISSUE TITLE
Update kotlinTest

### ISSUE THREAD

**Issue by AdrianRaFo** [47deg/helios#17]
From 2.x.x to 3.x.x.

The test should use the JUnit runner with the new version

More info here : https://github.com/kotlintest/kotlintest
https://github.com/kotlintest/kotlintest/blob/master/doc/arrow-matchers.md

**Comment by AdrianRaFo** [comment]
At this moment this is not possible until the new Arrow version `0.9.0` was released with the required laws changes

**Comment by raulraja** [comment]
0.9.0 should come out in a couple of weeks max

**Comment by AdrianRaFo** [comment]
I still do it for this quarter then
