### ISSUE TITLE
Update detekt

### ISSUE THREAD

**Issue by AdrianRaFo** [47deg/helios#20]
We need to update https://github.com/arturbosch/detekt to the last version `RC 9.2` in maven and update the `detekt.yml` according to the kotlin style guide https://kotlinlang.org/docs/reference/coding-conventions.html

**Comment by AdrianRaFo** [comment]
The detekt version is already updated to `9.2` and related to the formatting issue we have this https://github.com/arturbosch/detekt/issues/652.
For now we have setted the `kotlin.code.style=official` on gradle properties to follow the official style rules.

**Comment by fedefernandez** [comment]
So, is this already done?

**Comment by AdrianRaFo** [comment]
Until the detekt issue was closed part of this is on hold, the other part is already done
