### ISSUE TITLE
Adds performance check to ci

### ISSUE THREAD

**Issue by AdrianRaFo** [47deg/helios#25]
We need to add a check ideally per PR in order to know if we are decreasing the benchmarks.

The easiest way could be a task to update the benchmark through the CI

**Comment by fedefernandez** [comment]
I've made some tests (see https://github.com/47deg/helios/tree/ff/beanchmarks-analyzer) and this is my proposal for this:
* Create a benchmark for helios only and execute it on each master merge and PR build (https://github.com/47deg/helios/compare/ff/improve-benchmarks?expand=1)
* On each master merge, commit and push the benchmark csv to one directory (with `[ci skip]`)
* On each PR build, compare the current csv with the one created from master
* Add a comment in the PR with the differences
* Update the PR status with a failure if there is a degradation below to a specific percentage, determined by an environment variable in travis-ci (optional).

If that sounds good, I can create the issues for tackling that. It shouldn't be too complex, just a GitHub client that supports three of operations:
* commit files: https://developer.github.com/v3/repos/contents/
* create/update comments to PRs: https://developer.github.com/v3/pulls/comments/
* create status: https://developer.github.com/v3/repos/statuses/

And a benchmark comparator (I've made some initial approach [here](https://github.com/47deg/helios/tree/ff/beanchmarks-analyzer/helios-benchmarks/src/main/kotlin/helios/benchmarks/compare)).

@juanpedromoreno @AdrianRaFo @raulraja @pakoito @nomisRev thoughts?

**Comment by raulraja** [comment]
This sounds great Fede. Have we looked into potential existing Gradle plugins for jmh that would do this already ? Also if we implement it ourselves it should probably be a Gradle plugin that does this generically for any project with jmh benchmarks and not just part of the Helios build. We need this for all the other arrow based libs too.

**Comment by juanpedromoreno** [comment]
Maybe we could upload those CSV to an external storage in the cloud, like Amazon S3 or GCS, grouped by release.

Also, another option, instead of comparing with the latest from master, it might be more consistent to compare benchmarks with the latest release?

**Comment by juanpedromoreno** [comment]
+1 for a gradle/sbt plugin.

**Comment by fedefernandez** [comment]
@raulraja I haven't found anything similar. I'm fine with creating a plugin, but that implies more time, that was my fear.

@juanpedromoreno good idea, we can abstract us from the external storage, again, making it more extensible and configurable requires more development time. Related to the release, I don't like it so much, it adds more complexity and you could see in your PR results that aren't because of your code.

If we go for a plugin, I guess we'd need to have one for gradle and another for sbt. Maybe having a common lib in kotlin for comparing results.
