### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by Octogonapus** [47deg/helios#85]
The `@json` annotation can only be used on data classes. I don't see why helios shouldn't support `enum` types as well. The enum value can be encoded as a `String`.

**Comment by raulraja** [comment]
@Octogonapus this will require some changes in the Arrow processor and we are currently heads down with arrow-meta which is based on compiler plugins. Once arrow-meta is available hopefully at the end of this year then the `@json` processor in Helios will be rewritten in terms of a compiler plugin which comes with KEEP-87 and type classes bundled in. This will allow any user or Helios directly derive encoders and decoders for enums and others currently not supported in Helios.

If you can't wait for that I can help you find the places in the current kapt processor where support for enums would need to be added in case you want to build that.

**Comment by Octogonapus** [comment]
I would have asked you to show me where I need to modify, but it sounds like that work would go to waste once we have arrow-meta. I guess I'll have to find another way in the meantime.

**Comment by raulraja** [comment]
What functionality from '@json' do you need for enums? If it's encoders and decoders you may be able just to write the boilerplate that the processor generates

**Comment by Octogonapus** [comment]
Yes, encoders and decoders. At some point I can look into writing what the processor would generate.

**Comment by raulraja** [comment]
Then it may be easy to just write those for enums similar to https://github.com/47deg/helios/blob/master/helios-core/src/main/kotlin/helios/instances/instancesJava.kt
