### ISSUE TITLE
Documentation in README.md

### ISSUE THREAD

**Issue by omainegra** [47deg/helios#9]
I know this project is still in development and not usable yet, but it looks very attractive, especially for people coming from **Scala** and **Circe**, so why don't put some effort into creating some sort of documentation, at least in the `README.md`. I believe it would help attract more developers to use and contribute to it.

**Comment by raulraja** [comment]
@omainegra thanks for your interest in Helios. We are getting close to a first alpha release and we will add docs right then. ETA a couple of weeks or so. I was just discussing yesterday with @nomisRev that we are usable for some of the most basic use cases and we can think of getting something out there for early adopters. I'll keep this issue open and close it as soon as we have the docs and a snapshot.

**Comment by omainegra** [comment]
That's great @raulraja. I'm looking forward to starting using it.

**Comment by fedefernandez** [comment]
We need to add a quickstart guide to the `README.md` file:
* How to add the dependency
* Basic usage
